# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
  - main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: ubuntu-custom
      image: mattgomes28/cpp-ubuntu-bionic:0.7

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: build_ubuntu_x86_64
    container: ubuntu-custom
    displayName: Ubuntu 18.04 Build
    continueOnError: false
    steps:
      - bash: |
          set -euo pipefail
          scripts/build_x86-64.sh unix-rel
          mkdir -p "$(Build.SourcesDirectory)/artifacts"
          tar -zcf "$(Build.Sourcesdirectory)/artifacts/build.tar.gz" "build"
        displayName: CMake Build & Package

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Build.SourcesDirectory)/artifacts"
          artifactName: UbuntuRelBuild
